export const EXPERIENCE = [
  {
    id: "gm",
    code: "GM",
    role: "Group Leader → Digital Enablement / Continuous Improvement",
    company: "General Motors",
    location: "Oshawa, ON",
    dates: "Sep 2025 – Present",
    year: "2025",
    size: "2x",
    photo: null, // typographic tile
    categories: ["engineering", "automotive", "leadership"],
    stack: ["Power BI", "Excel", "Databricks", "Power Automate", "Power Apps", "Manufacturing Systems", "JSON"],
    narrative:
      "As a Group Leader on the production floor (Sep 2025–Feb 2026), led hourly team members in a high-pressure automotive manufacturing environment — owning safety, quality, and responsiveness targets while hitting daily and monthly production counts. Worked directly with the union on scheduling and pay, and problem-solved in real time to prevent line stops, including root-causing defects and implementing controls to stop recurrence. Reported daily on issues, improvements, and ideas to plant leadership.\n\nMoved into a Continuous Improvement role (Mar 2026–Present), where I built and automated an SPQRC (Safety, People, Quality, Responsiveness, Cost) dashboard connected to Databricks, processing large production datasets with custom filters and data connections. Developed an AI agent that helps group leaders rewrite and optimize job instruction sheets for operators under strict formatting rules. Represented the production team in plant audits and drove cross-functional closure of audit findings against tight deadlines, and built several Power Apps automations for floor alerts and notifications.\n\nIndependently designed and built a full-stack app on Databricks Apps that reads real-time unit bank levels, target schedules, and downtime across multiple data schemas to help leaders make shift-staffing and overtime decisions — complete with a front-end dashboard, action buttons tied to backend automations, and an embedded AI agent used both as a chat interface and in backend logic.",
    bullets: [
      "Led hourly teams on the production floor, owning SPQRC targets and hitting daily/monthly production counts while working with the union on scheduling and pay.",
      "Root-caused defects and put controls in place to stop recurrence, reporting daily to plant leadership on issues and improvements.",
      "Built and automated an SPQRC dashboard on Databricks with custom filters across large production datasets.",
      "Developed an AI agent to help group leaders rewrite and optimize job instruction sheets under strict formatting rules.",
      "Represented production in plant audits and drove cross-functional closure of findings on tight deadlines; built Power Apps automations for floor alerts.",
      "Designed and shipped a full-stack Databricks Apps tool for real-time unit bank, schedule, and downtime visibility — with dashboard actions, backend automations, and an embedded AI agent.",
    ],
    links: [],
  },
  {
    id: "fsae",
    code: "FSAE",
    role: "High & Low Voltage Electrical (Member)",
    company: "UAlberta Formula Racing",
    location: "Edmonton, AB",
    dates: "May 2025 - Aug 2025",
    year: "2025",
    size: "1x",
    photo: null,
    categories: ["engineering", "automotive"],
    stack: ["KiCAD", "SolidWorks", "AutoCAD", "3D Printing"],
    narrative: "Joined the UAlberta Formula SAE team during my first season with the club, contributing to the high and low voltage electrical subsystem of the team's electric race car. As a new member, my focus has been on learning the team's standards, supporting senior members on schematic and layout work, and getting hands-on with the design tooling used in EV battery systems.",
    bullets: [
      "Supported the HV/LV electrical team in early system planning and component layout, using KiCAD for schematics and SolidWorks for mechanical fit.",
      "Studied FSAE technical regulations and the team's existing battery management system to understand safety, isolation, and packaging requirements.",
      "Engaged actively in technical meetings and workshops to build foundation skills I'll bring back to the team in the next development cycle.",
    ],
    links: [],
  },
  {
    id: "studentworks",
    code: "SWP",
    role: "Project Manager",
    company: "Student Works",
    location: "Edmonton, AB",
    dates: "May 2023 - Aug 2025",
    year: "2023–2025",
    size: "1x",
    photo: "/images/outdoorblinds.jpg",
    categories: ["leadership", "field"],
    stack: ["Field Operations", "Crew Coordination", "Client Communication", "Budget Tracking"],
    narrative: "Joined Student Works as a painter on the crew, then was promoted to Project Manager. Over three summers I went from working on sites myself to running multiple painting crews across Edmonton - scheduling, allocating painters by strength, visiting sites to keep work on track, and reporting up to leadership.",
    bullets: [
      "Coordinated multiple painting crews simultaneously, monitoring progress and pushing back delivery times to consistently beat project milestones.",
      "Reduced costs by approximately 20% through tighter delivery scheduling and crew-to-site matching based on individual strengths.",
      "Maintained sustained crew efficiency above 1.7x by communicating expectations clearly and supporting painters on-site when bottlenecks appeared.",
      "Built the management muscle I now rely on at GM - scheduling, accountability, and turning a team of individuals into a working unit.",
    ],
    links: [],
  },
  {
    id: "mkc",
    code: "MKC",
    role: "Coordinator (started as labour)",
    company: "Modern Kitchens & Construction",
    location: "Edmonton, AB",
    dates: "Mar 2020 - Aug 2024",
    year: "2020-2024",
    size: "1x",
    photo: "/images/customshelf.jpg",
    categories: ["leadership", "field"],
    stack: ["Blueprint Design", "Client Quotes", "Project Coordination", "Construction"],
    narrative: "Started as labour on the construction side - installing kitchens, working in clients' homes, learning the trade. Over four years I moved into a coordinator role: drafting custom blueprints, running quotes, managing the schedule across overlapping residential and commercial jobs, and working directly with clients through every stage. I also built MKC's website to help the company's online presence (currently being revamped).",
    bullets: [
      "Designed custom kitchen blueprints, presenting drawings to clients and revising them through to final approval before manufacturing.",
      "Coordinated multiple overlapping jobs by communicating with installers, suppliers, and clients to keep deadlines and quality standards aligned.",
      "Performed quotes for residential and commercial clients as part of the estimating team.",
      "Built MKC's company website (currently being revamped) to support customer outreach.",
    ],
    links: [
      // { label: "MKC Website ↗", url: "https://mkc-placeholder.com" }, // uncomment when ready
    ],
  },
];

export const EARLIER_EXPERIENCE = [
  {
    id: "hugoboss",
    code: "HB",
    role: "Sales Associate",
    company: "Hugo Boss",
    location: "Edmonton, AB",
    dates: "Apr - Aug 2023",
    year: "2023",
    size: "0.5x",
    photo: null,
    categories: ["field"],
    stack: ["Consultative Sales", "Client Retention", "Product Knowledge"],
    narrative: "Sales associate at Hugo Boss Premium Outlet during summer 2023. Recognized in district-level competitions for top performance and consistent target achievement.",
    bullets: [
      "Exceeded sales targets through a consultative approach, winning multiple district competitions.",
      "Built repeat-client relationships through detailed product knowledge and personalized outreach.",
      "Worked closely with the team to coordinate floor coverage and the customer experience end-to-end.",
    ],
    links: [],
  },
  {
    id: "bestbuy",
    code: "BB",
    role: "Omni / Fulfillment Specialist",
    company: "Best Buy",
    location: "Edmonton, AB",
    dates: "Oct 2021 - Oct 2022",
    year: "2021 - 2022",
    size: "0.5x",
    photo: null,
    categories: ["field"],
    stack: ["Customer Service", "Inventory", "Problem Solving"],
    narrative: "First retail role. Split time between Omni (customer-facing support and issue resolution) and Fulfillment (warehouse picking and order delivery to customers).",
    bullets: [
      "Awarded for selling the most memberships in the department (Nov 2021).",
      "Resolved customer issues at the support counter under time pressure, prioritizing a positive end-of-visit experience.",
      "Picked and delivered fulfillment orders accurately, building the warehouse memory needed to be efficient on the floor.",
    ],
    links: [],
  },
];

export const PROJECTS = [
  {
    id: "caraudio",
    code: "CA",
    role: "Full Audio System Rebuild",
    company: "Personal Project",
    location: "Garage Build",
    dates: "2024",
    year: "2024",
    size: "1x",
    photo: "/images/amplifier.jpg",
    gallery: ["/images/caraudio.jpg"],
    categories: ["automotive", "engineering"],
    stack: ["Hertz Amplifier", "Subwoofer Wiring", "Signal Routing", "Gain Tuning"],
    narrative: "Stripped and rebuilt the entire audio system in my car. Replaced every speaker, installed a new amplifier and subwoofer, ran power and signal lines from scratch through the chassis, and tuned the system end-to-end — gain matching, crossovers, and EQ.",
    bullets: [
      "Replaced all factory speakers with aftermarket components, sized to match the amplifier output.",
      "Installed and wired a new amplifier and subwoofer, including running power directly from the battery and routing signal lines cleanly through the chassis.",
      "Tuned the system manually - set gains by listening for distortion onset, configured high-pass and low-pass crossovers per channel, and tweaked subsonic filters.",
      "Diagnosed and resolved several wiring issues during install without an extra set of hands.",
    ],
    links: [],
  },
  {
    id: "motorcycle",
    code: "MO",
    role: "Yamaha R3 — General Maintenance",
    company: "Personal Project",
    location: "Edmonton, AB",
    dates: "2023 - Present",
    year: "2023+",
    size: "1x",
    photo: "/images/motorcycles.jpg",
    gallery: ["/images/oilchange_gadget.jpg"],
    categories: ["automotive"],
    stack: ["Engine Maintenance", "Clutch Mechanics", "General Upkeep"],
    narrative:
      "Bought a Yamaha R3 as a cheaper alternative to a car and used it as a hands-on learning project. Focused on general maintenance — oil and filter changes, getting familiar with the clutch, and a few cosmetic upgrades — nothing more ambitious than that.",
    bullets: [
      "Performed full oil and filter changes solo (improvised a funnel from a cut water bottle when the angle didn't work - got the job done).",
      "Studied the clutch mechanism end-to-end to understand torque transfer, lever feel, and slip behavior.",
      "Completed light cosmetic upgrades while keeping the work to general maintenance rather than performance tuning.",
    ],
    links: [],
  },
  {
    id: "pillpal",
    code: "PP",
    role: "PillPal - Pill Dispenser (HackED Beta Winner)",
    company: "Hackathon",
    location: "Edmonton, AB",
    dates: "Nov 2024",
    year: "2024",
    size: "1x",
    photo: null,
    categories: ["engineering"],
    stack: ["HTML/CSS", "Bootstrap", "C++", "Node.js", "Express", "Raspberry Pi Pico H"],
    narrative: "Built an automated pill-dispensing system for elderly users in 24 hours at HackED Beta. Combined a Raspberry Pi Pico H for hardware control with a Node/Express backend and an accessibility-focused front-end. Won the DivE Accessibility Category against 100+ other students.",
    bullets: [
      "Designed the front-end interface focused on accessibility - high-contrast active and hover states, large touch targets, and simple navigation.",
      "Programmed the Raspberry Pi Pico H to control the dispensing mechanism on a schedule, with audio-visual reminders for missed doses.",
      "Integrated hardware and software through a Node/Express backend so dispensing events and confirmations sync reliably.",
      "Won the DivE Accessibility Category in a field of 100+ participants.",
    ],
    links: [],
  },
  {
    id: "freespeech",
    code: "FR",
    role: "FreeSpeech - EEG-to-Text (NATHacks)",
    company: "Hackathon",
    location: "Edmonton, AB",
    dates: "Nov 2024",
    year: "2024",
    size: "1x",
    photo: null,
    categories: ["engineering"],
    stack: ["Python", "Tkinter", "Muselsl", "Random Forest", "XGBoost", "Petal Metrics"],
    narrative: "Built a non-verbal communication tool that reads EEG data from a Muse2 headset and translates motor-thought signals (\"left,\" \"right,\" \"blink\") into UI input. Real-time data streaming, machine-learning classification, and a Tkinter front-end - all in a hackathon timeframe.",
    bullets: [
      "Streamed real-time EEG data from a Muse2 headset using the Muselsl library and Petal Metrics software.",
      "Trained Random Forest and XGBoost models on the captured EEG streams to classify motor-thought commands.",
      "Achieved roughly 70% prediction accuracy on the target commands, enough for a working demo.",
      "Built a Tkinter GUI that the user could control hands-free through the EEG pipeline.",
    ],
    links: [],
  },
  {
    id: "designproject",
    code: "BS",
    role: "Edmonton Bus Shelter Redesign (Team Lead)",
    company: "ENGG 130 - UAlberta",
    location: "Edmonton, AB",
    dates: "Jan - Apr 2024",
    year: "2024",
    size: "1x",
    photo: "/images/3dmodel.jpg",
    categories: ["engineering", "leadership"],
    stack: ["TinkerCAD", "PrusaSlicer", "SketchUp", "Excel", "PowerPoint"],
    narrative: "Led a team of four engineers to redesign Edmonton's bus shelter from scratch within a fixed budget, then 3D-printed a scaled physical model. Presented to an audience of 200+ and earned a perfect 100% on project, presentation, and team cooperation.",
    bullets: [
      "Led a team of 4 engineers from concept to printed prototype within a fixed budget.",
      "Modeled the shelter in TinkerCAD and produced the physical scale model on a Prusa printer.",
      "Held weekly check-ins with each subdivision to keep work aligned with deadlines.",
      "Lead presenter to a 200+ audience; team scored a perfect 100%.",
    ],
    links: [],
  },
  {
    id: "embedded",
    code: "EM",
    role: "Embedded Systems & Lab Work",
    company: "UAlberta Coursework + Personal",
    location: "Edmonton, AB",
    dates: "2024 - Present",
    year: "ongoing",
    size: "1x",
    photo: "/images/microcontroler.jpg",
    categories: ["engineering"],
    stack: ["VHDL", "Arduino", "Raspberry Pi", "Digilent Analog Discovery", "C/C++"],
    narrative: "Ongoing coursework and personal experimentation with FPGAs, microcontrollers, and embedded development. Course projects with FPGA dev boards and the Analog Discovery 2 plus side projects with Arduino - building toward more substantial embedded work as I move through the program.",
    bullets: [
      "Worked with FPGA development boards and a Digilent Analog Discovery 2 in coursework, writing VHDL and verifying signals on the bench.",
      "Started Arduino-based personal projects to explore microcontroller programming outside coursework.",
      "Tile will grow as more projects come online - placeholder for ongoing embedded work.",
    ],
    links: [],
  },
  {
    id: "portfolio",
    code: "WB",
    role: "This Portfolio Website",
    company: "Personal Project",
    location: "Self-built",
    dates: "2026",
    year: "2026",
    size: "1x",
    photo: null,
    categories: ["engineering"],
    stack: ["Next.js", "Tailwind v4", "GSAP", "ScrollTrigger", "Vercel"],
    narrative: "The site you're on right now. Built from scratch in Next.js with route-based navigation, a custom intro animation, page transitions, and dual light/dark theming. Inspired by Jasmine Gunarto and Julia Krantz; everything else is mine.",
    bullets: [
      "Designed and built every page, including the intro animation, navbar, and the page-transition curtain system.",
      "Implemented dark/light theming with CSS variables and persistent preference via localStorage.",
      "Heavy use of GSAP and ScrollTrigger for entry animations, replays on scroll, and per-letter hover effects.",
      "Deployed on Vercel with auto-deploys from GitHub.",
    ],
    links: [
      { label: "GitHub ↗", url: "https://github.com/ssbansal3/Sim-ran-s-Port-folio-" },
    ],
  },
];
